# Generated by Django 4.2.3 on 2023-07-12 10:40

import authModule.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[authModule.utils.valid_name])),
                ('age', models.DateField(default=None)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[authModule.utils.valid_email])),
                ('phone_num', models.CharField(max_length=50, unique=True, validators=[authModule.utils.valid_phone_num])),
                ('is_active', models.BooleanField(default=True)),
                ('is_phone_num_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
